server:
  port: 8080
  servlet:
    session:
      # cookie安全配置
      cookie:
        http-only: true # 浏览器脚本将无法访问cookie
        secure: false # 仅通过HTTPS连接发送cookie，HTTP无法携带cookie


spring:
  session:
    timeout: 15m # 会话超时时间配置(优先级更高)最少一分钟，登录过期需要重新登录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity_oath2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/

logging:
    config: classpath:log4j2-dev.xml

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true
